(() => {
  'use strict';
  const ME={github:'https://github.com/Hxrdik-24',linkedin:'https://www.linkedin.com/in/hardik-prajapati-475231390',email:'hardikprajapati2008@gmail.com'};
  const project=(id,title,description,tech,status,features,repo,extra={})=>({id,kind:'pad',label:title,title,description,tech,status,features,repo:`${ME.github}/${repo}`,...extra});
  // Portfolio facts are intentionally kept in one place and limited to repository evidence.
  const NODES=[
    {id:'about',kind:'lotus',label:'About',title:'A curious builder',body:['I’m Hardik Prajapati, a BCA student interested in full-stack development and cybersecurity. I prefer learning by making working projects: small tools, web applications, security experiments and unusual interfaces.','The pond is a quieter way to browse that work. Open a lily pad for a project, or visit the other objects for the longer view.']},
    {id:'skills',kind:'pebbles',label:'Skills',title:'Tools I actually use',groups:{Programming:['Python','Java'],Web:['HTML','CSS','JavaScript','Flask'],Data:['SQLAlchemy','PostgreSQL','SQLite'],Security:['Scapy','socket programming','PCAP analysis','network reconnaissance','CTF practice'],Tools:['Git','Rich','Pyrogram','Pillow','OpenCV','Requests']}},
    project('blog','H-24 Blog','A Flask blog for accounts, profiles and short-form posts.','Python · Flask · SQLAlchemy · PostgreSQL · Redis','Prototype / active development',['Registration and login with Flask-Login','Email verification and profile images','Caching, rate limiting and basic security headers'], 'H-24_Blog'),
    project('ids','Nexa IDS','A Python network security tool that captures live traffic, records packet details and produces AI-assisted reports.','Python · Scapy · Pandas · Requests','Active development',['Live packet sniffing','Structured CSV traffic logs','AI analysis through the Pollinations API'], 'Nexa_IDS'),
    project('sentinel','NetSentinel-v2','A multi-threaded local-network reconnaissance and OS-fingerprinting tool.','Python · socket · threading · Requests','Experimental / active',['Parallel host discovery','TTL-based OS guesses','MAC and vendor information lookup'], 'NetSentinel-v2'),
    project('pcap','PCAP Analyzer','A CTF-oriented packet-capture analyzer for extracting network details, readable payload strings and possible flags.','Python · Scapy','Educational tool',['IP and protocol extraction','Payload string discovery','User-defined or default flag format search'], 'PCAP-Analyzing-Tool-'),
    project('hub','H-24 Hub','A terminal cloud-storage experiment using Telegram Saved Messages for compressed backups and file management.','Python · Pyrogram · Rich · asyncio','Active development',['ZIP compression and upload/download flows','Progress tracking and repository browsing','Optional file encryption and key-based decryption'], 'H-24_Hub'),
    project('pixels','PixelShifter','An experimental Python toolkit for turning images and video into terminal or browser ASCII visuals.','Python · Pillow · OpenCV · pygame','Experimental',['Background removal','Colored HTML ASCII output','Batch image conversion and video playback'], 'PixelShifter'),
    {id:'cyber',kind:'lantern',label:'Cybersecurity',title:'Learning security by building',body:['My security work is practical and educational: packet analysis, local-network reconnaissance, CTF-style investigation and defensive-minded web development.','The repositories show experiments with Scapy, sockets, PCAP files, authentication, rate limiting, security headers and environment-based secrets. They are learning projects — not a claim of professional penetration-testing experience.'],links:[['GitHub security projects',`${ME.github}?tab=repositories&q=security`]]},
    {id:'journey',kind:'stones',label:'Journey',title:'A workbench, not a résumé',body:['The repository history shows a progression from small Python utilities and networking exercises toward larger assistants, security tools, Flask applications and interactive portfolio experiments.','I’m currently focused on strengthening fundamentals, making projects more complete, and documenting what I learn. No dates are shown here where the repository evidence is unclear.']},
    {id:'contact',kind:'boat',label:'Contact',title:'Say hello',body:['The best place to follow the work is GitHub. For a direct message, email is open for portfolio, project and internship conversations.'],links:[['GitHub',ME.github],['LinkedIn',ME.linkedin],['Email',`mailto:${ME.email}`]]}
  ];
  const $=s=>document.querySelector(s), canvas=$('#pond'),ctx=canvas.getContext('2d'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  let W=0,H=0,scale=1,clock=0,raf=0,last=0,season='summer',opened=new Set(),activeButton=null;
  const pointer={x:-1000,y:-1000,active:false}, food=[];
  const koi=Array.from({length:7},(_,i)=>({x:Math.random(),y:Math.random(),vx:(Math.random()-.5)*.04,vy:(Math.random()-.5)*.04,h:i===6}));
  const color={summer:['#39736b','#1e4b4d'],rain:['#526d75','#263e4a'],winter:['#8ba7ad','#3c6068'],night:['#273b59','#111f32']};
  const pos={about:[.50,.46],skills:[.20,.27],blog:[.66,.70],ids:[.29,.64],sentinel:[.80,.30],pcap:[.58,.19],hub:[.80,.52],pixels:[.43,.83],cyber:[.90,.58],journey:[.10,.51],contact:[.85,.84]};
  const isProject=n=>n.repo;
  function resize(){const d=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;scale=Math.min(W,H)/620;canvas.width=W*d;canvas.height=H*d;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(d,0,0,d,0,0);layout();draw()}
  function xy(n){const p=pos[n.id],portrait=H>W;return[(portrait&&n.id==='contact'?.78:p[0])*W,(portrait&&n.id==='contact'?.88:p[1])*H]}
  function layout(){NODES.forEach(n=>{if(n.button){const[x,y]=xy(n);n.button.style.left=x+'px';n.button.style.top=y+'px'}})}
  function round(x,y,r,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}
  function draw(){const g=ctx.createLinearGradient(0,0,0,H),c=color[season];g.addColorStop(0,c[0]);g.addColorStop(1,c[1]);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<5;i++){const x=W*(.15+i*.2)+Math.sin(clock*.08+i)*40,y=H*(.2+i*.13),r=Math.max(W,H)*.3,q=ctx.createRadialGradient(x,y,0,x,y,r);q.addColorStop(0,'#8bb8a51c');q.addColorStop(1,'transparent');ctx.fillStyle=q;ctx.fillRect(0,0,W,H)}
    koi.forEach(fish=>{fish.x=(fish.x+fish.vx*(season==='winter'?.45:1)/60+1)%1;fish.y=(fish.y+fish.vy*(season==='winter'?.45:1)/60+1)%1;const x=fish.x*W,y=fish.y*H;ctx.save();ctx.translate(x,y);ctx.rotate(Math.atan2(fish.vy,fish.vx));ctx.fillStyle=fish.h?'#f7f0d6':'#d9744a';ctx.globalAlpha=.82;ctx.beginPath();ctx.ellipse(0,0,15*scale,6*scale,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f3ecdc';ctx.beginPath();ctx.arc(4*scale,-1*scale,2*scale,0,Math.PI*2);ctx.fill();ctx.restore()});
    NODES.forEach((n,i)=>{const[x,y]=xy(n),r=n.kind==='lotus'?38:n.kind==='lantern'?22:28;ctx.globalAlpha=.28;round(x+4,y+7,r,'#071c1c');ctx.globalAlpha=1;round(x,y,r,n.kind==='lotus'?'#d995a6':n.kind==='lantern'?'#8c8d78':n.kind==='pebbles'?'#898a82':n.kind==='stones'?'#85877d':n.kind==='boat'?'#eee2c6':'#477e59');if(n.kind==='lotus'){round(x,y,13,'#efbd9e')}if(n.kind==='lantern'){round(x,y-2,9,'#f4bf70')}if(n.button&&n.button.matches(':hover,:focus-visible')){ctx.strokeStyle='#f0bd91';ctx.lineWidth=2;ctx.stroke()}});ctx.globalAlpha=1}
  function step(t){const dt=Math.min((t-last)/1000,.05);last=t;clock+=dt;if(!reduced)draw();raf=requestAnimationFrame(step)}
  function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('on');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('on'),3400)}
  function addText(parent,tag,text){const el=document.createElement(tag);el.textContent=text;parent.append(el);return el}
  function content(n,titleId){const f=document.createDocumentFragment();const h=addText(f,'h2',n.title);if(titleId)h.id=titleId;if(n.description)addText(f,'p',n.description);if(n.body)n.body.forEach(x=>addText(f,'p',x));if(n.groups)Object.entries(n.groups).forEach(([group,items])=>{addText(f,'h3',group);addText(f,'p',items.join(' · '))});if(n.tech||n.status||n.features){const dl=document.createElement('dl');dl.className='meta';[['Tech',n.tech],['Status',n.status]].forEach(([k,v])=>{if(v){addText(dl,'dt',k);addText(dl,'dd',v)}});f.append(dl);if(n.features){addText(f,'h3','What it includes');const ul=document.createElement('ul');n.features.forEach(x=>addText(ul,'li',x));f.append(ul)}}if(n.links||n.repo){const links=document.createElement('div');links.className='links';(n.links||[]).forEach(([label,url])=>link(links,label,url));if(n.repo)link(links,'GitHub repository',n.repo);f.append(links)}return f}
  function link(parent,label,url){const a=addText(parent,'a',label);a.href=url;a.target='_blank';a.rel='noopener noreferrer'}
  function open(n){activeButton=n.button;$('#panel-content').replaceChildren(content(n,'panel-title'));$('#panel').classList.add('open');$('#panel').setAttribute('aria-hidden','false');$('#panel-close').focus();opened.add(n.id);draw()}
  function close(){const p=$('#panel');p.classList.remove('open');p.setAttribute('aria-hidden','true');if(activeButton)activeButton.focus()}
  function buildPlain(){const wrap=document.createElement('div');const intro=document.createElement('div');intro.className='plain-intro';addText(intro,'h1','Hardik Prajapati');addText(intro,'p','BCA student building software, security tools and experimental projects.');wrap.append(intro);NODES.forEach(n=>{const s=document.createElement('section');s.append(content(n));wrap.append(s)});$('#plain').append(wrap)}
  function setup(){NODES.forEach(n=>{const b=document.createElement('button');b.className='hot';b.type='button';b.setAttribute('aria-label',`${n.label}: ${n.title}`);b.addEventListener('click',()=>open(n));b.addEventListener('focus',draw);b.addEventListener('blur',draw);n.button=b;$('#hotspots').append(b)});buildPlain();$('#panel-close').addEventListener('click',close);document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});$('#plain-toggle').addEventListener('click',e=>{const on=$('#plain').hidden;$('#plain').hidden=!on;$('#hotspots').hidden=on;$('#pond').style.visibility=on?'hidden':'visible';e.currentTarget.textContent=on?'Back to the pond':'Plain version';e.currentTarget.setAttribute('aria-pressed',String(on));if(on)$('#plain').querySelector('a')?.focus()});document.querySelectorAll('[data-season]').forEach(b=>b.addEventListener('click',()=>{season=b.dataset.season;document.querySelectorAll('[data-season]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));draw();toast(`${b.textContent}. The pond changes its light.`)}));canvas.addEventListener('pointermove',e=>{pointer.x=e.clientX;pointer.y=e.clientY;pointer.active=true});canvas.addEventListener('pointerleave',()=>pointer.active=false);canvas.addEventListener('pointerdown',e=>{if(food.length<8){food.push({x:e.clientX,y:e.clientY,t:1});toast('The koi noticed.')};$('#hint').classList.add('gone')});$('#sound-toggle').addEventListener('click',e=>{toast('Sound stays off by default — the pond should be quiet.');e.currentTarget.setAttribute('aria-pressed','false')});resize();if(reduced)draw();else raf=requestAnimationFrame(step);setTimeout(()=>$('#hint').classList.add('gone'),12000)}
  addEventListener('resize',resize);setup();
})();
